### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [mukswilly/udpgw#1]
used the ff ;
x/org/crypto/ssh
eycorsican/go-tun2socks

Video and Voice calls,
VoIP is not supported

**Comment by mukswilly** [comment]
I think you’re on the wrong repo. This repo deals with running a udpgw server.

**Comment by ghost** [comment]
> I think you’re on the wrong repo. This repo deals with running a udpgw server.

Your link is gone https://github.com/mukswilly/go-tun2socks

**Comment by mukswilly** [comment]
Yes, it is no more and it's not connected to this repo.

**Comment by ghost** [comment]
> Yes, it is no more and it's not connected to this repo.

Ok. Can you share tbe deleted repo then?

**Comment by mukswilly** [comment]
I don’t have it. However, you can code something of your own basing on this https://github.com/Psiphon-Labs/psiphon-tunnel-core/blob/5c99afdb33994e95b99e7ee7c7e79e3429759276/psiphon/server/udp.go
